Title: 

A Reason, A Season, A Lifetime

----

Legacy-url: 

http://blog.melmyfinger.com/5353

----

Legacy-pub-date: 

Sun, 20 Jul 2014 07:01:27 +0000

----

Legacy-guid: 

http://blog.melmyfinger.com/?p=5353

----
Author: melmyfinger
----

Body: 

People come into your life for a reason, a season or a lifetime.

> 

> When you figure out which one it is,

> you will know what to do for each person.

> 

> When someone is in your life for a **reason**,

> it is usually to meet a need you have expressed.

> They have come to assist you through a difficulty;

> to provide you with guidance and support;

> to aid you physically, emotionally or spiritually.

> They may seem like a godsend, and they are.

> They are there for the reason you need them to be.

> 

> Then, without any wrongdoing on your part or at an inconvenient time,

> this person will say or do something to bring the relationship to an end.

> Sometimes they die. Sometimes they walk away.

> Sometimes they act up and force you to take a stand.

> What we must realize is that our need has been met, our desire fulfilled; their work is done.

> The prayer you sent up has been answered and now it is time to move on.

> 

> Some people come into your life for a **season**,

> because your turn has come to share, grow or learn.

> They bring you an experience of peace or make you laugh.

> They may teach you something you have never done.

> They usually give you an unbelievable amount of joy.

> Believe it. It is real. But only for a season.

> 

>**Lifetime** relationships teach you lifetime lessons;

> things you must build upon in order to have a solid emotional foundation.

> Your job is to accept the lesson, love the person,

> and put what you have learned to use in all other relationships and areas of your life.

> It is said that love is blind but friendship is clairvoyant.

----

Excerpt: 



----

Legacy-id: 

5353

----

Theme: 

A01

----

Date: 

2014-07-20

----

Legacy-date: 

2014-07-20 00:01:27

----

Legacy-date-gmt: 

2014-07-20 07:01:27

----

Legacy-slug: 

a-reason-a-season-a-lifetime

----

mentions: 

inchaioki

----

Legacy-post-format: 

quote

----

Categories: 

wisdom

----

Featured-name: 



----

Featured-title: 



----

Featured-source-name: 



----

Source-name: 

Unknown

----

Source-url: 



----

Via-name: 

inchaioki

----

Via-url: 



----

Legacy-via: 



----

Is-featured: 



----

Legacy-is-private: 

