Title: Hi, My Name is Mel.

----

Body: 

When Mel is not eating, he's flexing his internet muscles to stay on top of music on YouTube, social media trends, tech news, web standards, and Apple rumors that tickle his impulsive-shopping disorder.

For the past two summers, Mel co-organized The Featured Acoustic Playlist (FAP) benefit concert in San Diego, CA. The goal of the annual event is to showcase undiscovered YouTube & local talent, inspire music in today's youth, bring together online & offline communities, and raise money for charity.

When Mel is AFK, he's usually eating In-N-Out, supporting his musically-talented friends at shows, tweeting from the toilet with his iPad, or bullying little kids on the basketball court.

Currently residing in Los Angeles, Mel is taking time off work to pursue personal projects, such as writing awkward bios about himself in third person.

----

Excerpt: 

----

Date: 2010-05-21

----

Source-name: 

----

Source-url: 

----

Via-name: 

----

Via-url: 

----

Mentions: 

----

Is-featured: 1

----

Featured-name: 

----

Featured-title: 

----

Featured-source-name: 

----

Meta-title: 

----

Meta-description: 

----

Hashtags: 

----

Author: melmyfinger, meltajon

----

Body-personal: 

I've been sitting on the age 23 for a few years now.  I'm Filipino.  Youngest of three brothers, born in California.  Raised in Saudi Arabia.

I was never the guy that wanted the spotlight or to be the center of attention.  I've always been about surrounding myself with genuine, loving, down-to-earth people that appreciate their lives and inspire me to do the same.  Because honestly, growing up in the middle of the desert in Saudi Arabia, there wasn't much to do but appreciate good company.  And every time I find myself in a group like that, I do everything I possibly can to keep that group together.

My love for good company and my inner-geek has always played a part in who I am today.  Just looking back on the last twenty-something years, I can see that this has always been the case:

* In middle school, I was a moderator for this dial-up BBS called Sandbyte (First Class Client!).
* In college I started a messageboard called JustBBall.com, which I grew to 12,000 members in 3.5 years before selling it.
* Throughout college, I ran a site called the577, which was dedicated to keeping me and my childhood friends connected since moving on from our beloved little town in the middle of no where.
* Since graduating, I've been working for an internet software company that allows other companies have their own social network.
* In late summer 2008, I fell for a group of people on blogTV.  I've never met so many amazing, talented, good-hearted people in such a short amount of time.  BTVfam: "When I first met you, I had no idea how important you'd be to me."

I used to believe in "forever" but now I'm not so sure.  I've learned that good things tend to come and go, and life tends to pull you from the very people you love.  Some things you have no control over...and that's life.

So I've taught myself that no matter what is happening to me, I will cherish every moment of it.  And every person that walks into my life, I hug them like it's the first and last time.  

As each chapter of my life ends and new ones begin, characters come and go.  New stories emerge, with new dramas and romances, with new ups and downs...but the same theme remains every time: 

Continue to love, laugh, and learn.

To be passionate about something and let it be my constant; be my guiding light; my north star.  To appreciate and find humor in even the simplest things.  To take risks and be able to say "Fuck it, why not?  It might change my life."  To follow my heart, even if it may end up in heartbreak.  To make mistakes —  lots of mistakes —  but learn from every single one.

These are things that I have always wished upon myself.  And if I'm fortunate enough to have you following me on Facebook, Twitter, Tumblr or whatever...with every single thing that I share, I hope to make you smile or at least leave some kind of impression on you.  Because these very things that I wish upon myself, I wish for you as well.

Love, laugh, and learn.

-Mel

----

Categories: about