Author: melmyfinger, meltajon

----

Title: Quick Thoughts on the Samsung Galaxy S6 Unveiling

----

Date: 2015-03-01

----

Meta-title: 

----

Is-featured: 

----

Body: ## Observations

* It took 18 minutes before they said anything of substance at the announcement. The first 18 minutes was entirely fluffed with ambiguous marketing words like, "leading," "best," "innovative." Those are words that you should never say to describe yourself. Those are words should be **exemplified in your work**. It's like a guy trying to pick up a girl by saying, "I'm confident and attractive!"
* Hilarious: Samsung makes big deal of Galaxy S6 "Edge" curved screen. AND THEN NEVER SAYS WHY THAT'S BETTER. (via [@amir](https://twitter.com/amir/status/572095493574135808))
* Samsung owners the last 5 years: “iPhone sucks! No removable battery or SD card and plastic is so much more durable!” The S6 —> “Um, oops”. (via [@HilzFuld](https://twitter.com/HilzFuld/status/572093949847842816))
* Their camera comparison vs. an iPhone 6 Plus was a joke. — RT [@BenBajarin](https://twitter.com/BenBajarin/status/572095148307312640): Samsung clearly doesn’t know how to tap on the iPhone screen on the subjects to change the lighting.
* Samsung's new mantra: “Design with purpose." It took them this long to realize that??
* The [bottom of the Galaxy S6](https://twitter.com/verge/status/572092869386891264) sure looks like an iPhone 6.

## The Good

* Screen looks great, as expected by the company that makes the best screens in the industry.
* The shiny colored back screens look really, really great.
* Fast charging is AWESOME. Charging for 10 minutes to get 4 hours of battery life is a game changer.
* Selfie camera looks great and is something that Samsung should keep pushing. Because, let's face it, everyone loves a good selfie. The selfie camera is a very humanized technology.
* The upgraded Gorilla Glass is an evolutionary improvement; eventually all smartphones will have it.
* The overall hardware build quality looks FANTASTIC. No more metallic-painted plastic. For the first time, it looks like Samsung has a premium device that will actually *feel* like a premium device in your hand.

## The Bad

* Looks like they removed the water-resistance from Galaxy line this year. That's a shame. That was a really great feature that really should become the standard.

## Questions

* Does the curved screen make any significant improvements to the viewing experience? Do videos really look any better?
* How long will the battery last in the real world? Samsung has been known for [cheating benchmarks before](http://www.theregister.co.uk/2013/11/26/samsung_and_htc_face_android_3d_graphics_test_delisting_shame/).
* How well will the battery hold charges over time? Does fast charging mean the battery will degrade faster than normal?
* The fingerprint scanner has been redone to work more like the iPhone's because the old swipe version was shit. Will this new fingerprint scanner be as technically reliable as Touch ID?
* Does fast charging work over wireless charging? Or is it an asterisk where the fast charging will only work when you plug it in?
* How successful will Samsung Pay be in the U.S.? Outside the U.S? They highlighted how only 10% of retailers support Apple Pay *right now*, but that number will significantly improve; the U.S. is in the middle of upgrading all merchants to the more secure, encryption chip-based point-of-sale system.
* Does Samsung get a cut or kickback of each Samsung Pay transaction?
* How well will this resonate with existing Samsung buyers? Is there a lot of pent up demand for a new Galaxy S by customers who were unimpressed with the past two models? Will this reverse the [downward trend](/p/ys21r1) of Samsung's mobile profits?
* If someone was on Samsung for the big screen, and went Apple when it matched that, will they move back again because Samsung dumped plastic? (via[@BenedictEvans](https://twitter.com/BenedictEvans/status/572098682390245377))

----

Excerpt: 

----

Meta-description: 

----

Source-name: 

----

Source-url: 

----

Via-name: 

----

Via-url: 

----

Categories: first-impressions,smartphones

----

Mentions: 

----

Hashtags: samsung,samsung-galaxy,samsung-galaxy-s6

----

Meta-keywords: 

----

Featured-name: 

----

Featured-title: Samsung Galaxy S6 Edge

----

Featured-source-name: The Verge