Title: iPhone 6:  First Impressions

----

Date: 2014-09-20

----
Author: melmyfinger, meltajon
----

Body: It's definitely an adjustment, sacrificing one-handed accessibility for a larger screen. It's a little harder to take food pics lol, and I found myself having to use both hands when reading while lying in bed. But because of my bad vision in my right eye, I can definitely appreciate the larger screen for reading.

I have yet to really play with the camera but I've definitely noticed it's improved ability for taking photos in low-light conditions.

I'm really excited to test out the quick autofocus with my puppy; taking non-blurry pics of a hyper pup is one of the hardest thing to do.

My only real complaint is a temporary one -- most third-party apps haven't been redesigned to support the larger screen yet, so they all look like blown-up zoomed versions of the 5S. Surely this will become a non-issue soon.

----

Excerpt: 

----

Source-name: 

----

Source-url: 

----

Via-name: 

----

Via-url: 

----

mentions: 

----

hashtags: iphone-6,iphone,apple

----

Categories: smartphones, first-impressions

----

Is-featured: 

----

Featured-name: 

----

Featured-title: 

----

Featured-source-name: 

----

Meta-title: 

----

Meta-description: 

----

Meta-keywords: 