Title: Create

----

Date: 2015-01-21

----

Meta-title: 

----

Is-featured: 

----
Author: melmyfinger
----

Body: [Jennifer Chung](https://www.facebook.com/jaeyunchung/posts/10204733320826662):

> Creators, remember this:

> Some people are gonna hate your work. They'll turn their eyes away, close their ears, and sometimes even take the time to let you and others know how much they despise you.

> But there are also going to people that love what you create. It may widen their eyes, open their ears, and even their hearts for the first time in a long time. They may even let you know how much you've changed their lives with the work that you've done and share with you stories that may inspire you to create even more.

> So create. You have a purpose and don't worry about whether or not it will please everyone, because I guarantee you it won't. You can make a difference with what you love to do to the people who are meant to be changed by what you create.

> As for the people who hate, forgive them, and pray that soon they'll encounter something that changes their lives for the better; that beauty will be revealed to them in everything no matter how different something may be to their standard, so that they can better love in general, rather than resort to hate due to their lack of ability to tap into good.

> "I have decided to stick with love. Hate is too great a burden to bear." - Martin Luther King, Jr.

----

Excerpt: 

----

Meta-description: 

----

Source-name: Jennifer Chung

----

Source-url: https://www.facebook.com/jaeyunchung/posts/10204733320826662

----

Via-name: 

----

Via-url: 

----

Categories: inspiration

----

Mentions: jennifer-chung

----

Hashtags: 

----

Meta-keywords: 

----

Featured-name: 

----

Featured-title: 

----

Featured-source-name: 