Title: Being a Great Innovator

----

Date: 2014-09-11

----
Author: melmyfinger, meltajon
----

Body: [Walter Isaacson on Tim Cook](http://www.usatoday.com/story/tech/2014/09/09/tim-cook-interview-usa-today/15312749/):

> Being a great innovator requires linking vision to execution. Steve was an awesome visionary and he made sure the people around him could execute. Tim is a genius at execution, and in the next three years he has to show that he and his team can provide new visions that are disruptive.

----

Excerpt: 

----

Source-name: USA Today

----

Source-url: http://www.usatoday.com/story/tech/2014/09/09/tim-cook-interview-usa-today/15312749/

----

Via-name: 

----

Via-url: 

----

mentions: 

----

Categories: product-design

----

Is-featured: 

----

Featured-name: 

----

Featured-title: 

----

Featured-source-name: 

----

Meta-title: 

----

Meta-description: 

----

hashtags: 

----

Meta-keywords: 